#!/usr/bin/env python3
"""
apriltag_precision_test.py
==========================

ROS 1 (rospy) tool for measuring the precision of an AprilTag perception
pipeline using the printed test sheet generated by the companion PDF
(IDs 0-11 of the tag16h5 family at known positions in the sheet frame).

Workflow
--------
1. Place the printed sheet in view of your camera. Run this node.
2. Hit ENTER in the terminal -> snapshot 1 is captured by querying TF for
   the configured tag frames.
3. Move the sheet to a new pose. Hit ENTER again -> snapshot 2.
4. Repeat until at least N (default 5) snapshots have been collected.
5. Type 'q' + ENTER (or send EOF) to stop early; otherwise the report is
   produced automatically once N snapshots are reached.

What it computes
----------------
For every snapshot, for every PAIR of tags (i, j) visible in that snapshot,
we compute the relative transform T_ij = T_i^-1 * T_j (in the parent frame
of the TF lookup). The ground-truth relative transform T_ij_gt is computed
from the page-2 table baked into this script. Three families of error are
extracted per pair, then pooled across snapshots:

  (a) Centre-to-centre distance error:
        |t_ij|_meas - |t_ij|_gt   (signed scalar, mm)
        | |t_ij|_meas - |t_ij|_gt | (absolute scalar, mm)

  (b) Out-of-plane angle: angle between tag-z-axes of i and j, expressed
      as deviation from the ground-truth value (0 deg for a planar sheet).
      For a flat sheet, this is a direct measure of how much the pipeline
      'sees' tags as non-coplanar when they are in fact coplanar.

  (c) Full SE(3) relative pose error in the i-frame:
        translation: t_ij_meas - t_ij_gt (3 components, mm)
        rotation:    R_err = R_ij_meas * R_ij_gt^T
          - decomposed as roll/pitch/yaw (deg, intrinsic ZYX)
          - and as the SO(3) geodesic angle (deg, axis-angle magnitude)

Per-dimension distributions are summarised (mean, median, std, MAD,
percentiles) and matplotlib histograms are written to disk. A CSV of all
per-pair errors is also written for offline analysis.

Coordinate frames
-----------------
This script assumes ROS REP-103 conventions (right-handed, X forward,
Y left, Z up) for the parent frame. The ground-truth sheet frame from
page 2 of the PDF is image-style (X right, Y DOWN, theta = clockwise
about Z viewed from above the sheet), and is converted internally to a
right-handed sheet frame: X_sheet_rh = +X_pdf, Y_sheet_rh = -Y_pdf,
Z_sheet_rh = +Z_out_of_page. The yaw of each tag is therefore -theta_pdf
in the right-handed sheet frame.

The tag-pair RELATIVE transforms are invariant under the choice of parent
frame as long as both tags are looked up against the *same* parent in the
same snapshot. That is the only assumption we rely on.

Usage
-----
  rosrun <your_pkg> apriltag_precision_test.py \
      _frame_pattern:='tag_{:d}' \
      _parent_frame:='camera_link' \
      _tag_ids:='[0,1,2,3,4,5,6,7,8,9,10,11]' \
      _num_snapshots:=5 \
      _output_dir:='/tmp/apriltag_precision'

Dependencies
------------
  rospy, tf2_ros, geometry_msgs, numpy, scipy, matplotlib
"""

from __future__ import print_function

import csv
import math
import os
import select
import sys
import threading
from itertools import combinations

import numpy as np
import rospy
import tf2_ros
from geometry_msgs.msg import TransformStamped
from scipy.spatial.transform import Rotation as R

# Matplotlib without a display
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------------
# Ground-truth tag layout (matches page 2 of the calibration PDF)
# ---------------------------------------------------------------------------
# Format: id -> (cx_mm, cy_mm, theta_deg) in the PDF sheet frame
# (origin top-left, +X right, +Y DOWN, theta = clockwise about Z viewed from
#  above the page, i.e. theta>0 rotates +X towards +Y_pdf).
GROUND_TRUTH_PDF = {
    0:  (27.50,  27.50,  0.0),
    1:  (85.00,  27.50, 30.0),
    2:  (142.50, 27.50, 90.0),
    3:  (27.50,  80.00, 45.0),
    4:  (85.00,  80.00,  0.0),
    5:  (142.50, 80.00, 60.0),
    6:  (27.50,  135.00, 90.0),
    7:  (85.00,  135.00, 45.0),
    8:  (142.50, 135.00,  0.0),
    9:  (27.50,  192.50,  0.0),
    10: (85.00,  192.50, 30.0),
    11: (142.50, 192.50, 45.0),
}


def gt_pose_in_rh_sheet_frame(tag_id):
    """Return the ground-truth pose of tag_id in the right-handed sheet frame
    (X right, Y up, Z out-of-page) as a 4x4 homogeneous matrix in METRES.

    Conversion from the PDF (Y-down) frame:
        x_rh =  x_pdf
        y_rh = -y_pdf
        yaw_rh = -theta_pdf   (positive yaw is CCW about +Z_rh)
    """
    cx_mm, cy_mm, theta_deg = GROUND_TRUTH_PDF[tag_id]
    x_m = cx_mm * 1e-3
    y_m = -cy_mm * 1e-3
    yaw_rad = -math.radians(theta_deg)

    T = np.eye(4)
    T[:3, :3] = R.from_euler("z", yaw_rad).as_matrix()
    T[:3, 3] = [x_m, y_m, 0.0]
    return T


# ---------------------------------------------------------------------------
# SE(3) helpers
# ---------------------------------------------------------------------------

def transform_stamped_to_matrix(ts):
    """Convert a geometry_msgs/TransformStamped into a 4x4 numpy matrix."""
    t = ts.transform.translation
    q = ts.transform.rotation
    M = np.eye(4)
    M[:3, :3] = R.from_quat([q.x, q.y, q.z, q.w]).as_matrix()
    M[:3, 3] = [t.x, t.y, t.z]
    return M


def invert_se3(T):
    """Invert a 4x4 SE(3) matrix (cheaper than np.linalg.inv)."""
    Rm = T[:3, :3]
    t = T[:3, 3]
    Tinv = np.eye(4)
    Tinv[:3, :3] = Rm.T
    Tinv[:3, 3] = -Rm.T @ t
    return Tinv


def relative_transform(T_a, T_b):
    """T_a^-1 * T_b -- pose of b expressed in a's frame."""
    return invert_se3(T_a) @ T_b


def rotation_geodesic_deg(R1, R2):
    """Geodesic angle on SO(3) between two 3x3 rotation matrices, in degrees.
    Uses arccos((trace(R1^T R2) - 1) / 2) clamped for numerical safety."""
    Rd = R1.T @ R2
    cos_t = (np.trace(Rd) - 1.0) / 2.0
    cos_t = max(min(cos_t, 1.0), -1.0)
    return math.degrees(math.acos(cos_t))


def angle_between_vectors_deg(v1, v2):
    """Angle between two 3-vectors in degrees, clamped for numerical safety."""
    n1 = np.linalg.norm(v1)
    n2 = np.linalg.norm(v2)
    if n1 < 1e-12 or n2 < 1e-12:
        return float("nan")
    c = np.dot(v1, v2) / (n1 * n2)
    c = max(min(c, 1.0), -1.0)
    return math.degrees(math.acos(c))


# ---------------------------------------------------------------------------
# Snapshot capture
# ---------------------------------------------------------------------------

class TagSnapshotCapture(object):
    def __init__(self, tf_buffer, parent_frame, frame_pattern, tag_ids,
                 lookup_timeout=0.5):
        self.tf_buffer = tf_buffer
        self.parent_frame = parent_frame
        self.frame_pattern = frame_pattern
        self.tag_ids = tag_ids
        self.lookup_timeout = rospy.Duration(lookup_timeout)

    def capture(self):
        """Return dict {tag_id: 4x4 numpy matrix} of tags currently
        available in the TF buffer. Missing/stale tags are silently
        omitted (logged at DEBUG)."""
        snapshot = {}
        now = rospy.Time(0)  # latest available
        for tid in self.tag_ids:
            child = self.frame_pattern.format(tid)
            try:
                ts = self.tf_buffer.lookup_transform(
                    self.parent_frame, child, now, self.lookup_timeout)
            except (tf2_ros.LookupException,
                    tf2_ros.ConnectivityException,
                    tf2_ros.ExtrapolationException) as e:
                rospy.logdebug("TF lookup failed for %s: %s", child, e)
                continue
            snapshot[tid] = transform_stamped_to_matrix(ts)
        return snapshot


# ---------------------------------------------------------------------------
# Error computation
# ---------------------------------------------------------------------------

def compute_pair_errors(snapshot, gt_poses):
    """For each pair of tags visible in `snapshot`, compute error metrics
    against ground truth.

    snapshot:  dict tag_id -> 4x4 measured pose in parent frame
    gt_poses:  dict tag_id -> 4x4 ground-truth pose in sheet frame

    Returns: list of dicts, one per pair.
    """
    rows = []
    ids = sorted(snapshot.keys())
    for i, j in combinations(ids, 2):
        if i not in gt_poses or j not in gt_poses:
            continue
        T_i_meas = snapshot[i]
        T_j_meas = snapshot[j]
        T_i_gt = gt_poses[i]
        T_j_gt = gt_poses[j]

        T_ij_meas = relative_transform(T_i_meas, T_j_meas)
        T_ij_gt = relative_transform(T_i_gt, T_j_gt)

        t_meas = T_ij_meas[:3, 3]
        t_gt = T_ij_gt[:3, 3]
        R_meas = T_ij_meas[:3, :3]
        R_gt = T_ij_gt[:3, :3]

        # (a) Centre-to-centre distance error
        d_meas = np.linalg.norm(t_meas)
        d_gt = np.linalg.norm(t_gt)
        d_err_signed_mm = (d_meas - d_gt) * 1000.0
        d_err_abs_mm = abs(d_err_signed_mm)

        # (b) Out-of-plane: angle between tag-z-axes (= R[:,2] of each tag's
        # full pose, NOT the relative). This needs the raw measured z-axes
        # in the parent frame -- we compute it from T_i_meas and T_j_meas.
        z_i_meas = T_i_meas[:3, 2]
        z_j_meas = T_j_meas[:3, 2]
        z_i_gt = T_i_gt[:3, 2]
        z_j_gt = T_j_gt[:3, 2]
        zang_meas_deg = angle_between_vectors_deg(z_i_meas, z_j_meas)
        zang_gt_deg = angle_between_vectors_deg(z_i_gt, z_j_gt)
        zang_err_deg = zang_meas_deg - zang_gt_deg
        zang_err_abs_deg = abs(zang_err_deg)

        # (c) Full SE(3) relative pose error
        # Translation error in i-frame, mm per axis
        t_err_mm = (t_meas - t_gt) * 1000.0  # (dx, dy, dz)
        t_err_norm_mm = float(np.linalg.norm(t_err_mm))

        # Rotation error: R_err = R_meas * R_gt^T
        R_err = R_meas @ R_gt.T
        # Decompose to roll/pitch/yaw (intrinsic ZYX -> 'ZYX' in scipy)
        # Note: for small errors, the choice of decomposition is fine; for
        # large errors near gimbal lock the geodesic angle is the better
        # single-number summary.
        try:
            rpy_deg = R.from_matrix(R_err).as_euler("ZYX", degrees=True)
            yaw_err_deg, pitch_err_deg, roll_err_deg = rpy_deg
        except ValueError:
            roll_err_deg = pitch_err_deg = yaw_err_deg = float("nan")
        geo_err_deg = rotation_geodesic_deg(R_meas, R_gt)

        rows.append({
            "i": i, "j": j,
            "d_meas_m": d_meas, "d_gt_m": d_gt,
            "d_err_signed_mm": d_err_signed_mm,
            "d_err_abs_mm": d_err_abs_mm,
            "zang_meas_deg": zang_meas_deg,
            "zang_gt_deg": zang_gt_deg,
            "zang_err_deg": zang_err_deg,
            "zang_err_abs_deg": zang_err_abs_deg,
            "tx_err_mm": t_err_mm[0],
            "ty_err_mm": t_err_mm[1],
            "tz_err_mm": t_err_mm[2],
            "t_err_norm_mm": t_err_norm_mm,
            "roll_err_deg": roll_err_deg,
            "pitch_err_deg": pitch_err_deg,
            "yaw_err_deg": yaw_err_deg,
            "geo_err_deg": geo_err_deg,
        })
    return rows


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

# Each entry: (csv key, label, unit, abs?)
SCALAR_METRICS = [
    ("d_err_signed_mm",    "centre distance error (signed)",    "mm",   False),
    ("d_err_abs_mm",       "centre distance error (absolute)",  "mm",   True),
    ("zang_err_deg",       "z-axis angle deviation (signed)",   "deg",  False),
    ("zang_err_abs_deg",   "z-axis angle deviation (absolute)", "deg",  True),
    ("tx_err_mm",          "translation error tx (i-frame)",    "mm",   False),
    ("ty_err_mm",          "translation error ty (i-frame)",    "mm",   False),
    ("tz_err_mm",          "translation error tz (i-frame)",    "mm",   False),
    ("t_err_norm_mm",      "translation error norm",            "mm",   True),
    ("roll_err_deg",       "rotation error roll (ZYX)",         "deg",  False),
    ("pitch_err_deg",      "rotation error pitch (ZYX)",        "deg",  False),
    ("yaw_err_deg",        "rotation error yaw (ZYX)",          "deg",  False),
    ("geo_err_deg",        "rotation error SO(3) geodesic",     "deg",  True),
]


def summarise(values):
    """Return a dict of summary stats for an array-like of floats.
    NaNs are dropped before computing stats."""
    a = np.asarray(values, dtype=float)
    a = a[~np.isnan(a)]
    if a.size == 0:
        return {k: float("nan") for k in
                ("n", "mean", "median", "std", "mad", "min", "max",
                 "p05", "p25", "p75", "p95")}
    return {
        "n": int(a.size),
        "mean": float(np.mean(a)),
        "median": float(np.median(a)),
        "std": float(np.std(a, ddof=1)) if a.size > 1 else 0.0,
        "mad": float(np.median(np.abs(a - np.median(a)))),
        "min": float(np.min(a)),
        "max": float(np.max(a)),
        "p05": float(np.percentile(a, 5)),
        "p25": float(np.percentile(a, 25)),
        "p75": float(np.percentile(a, 75)),
        "p95": float(np.percentile(a, 95)),
    }


def print_report(all_rows, num_snapshots):
    print()
    print("=" * 78)
    print(" AprilTag Precision Test  -  Report")
    print("=" * 78)
    print(" Snapshots collected: {}".format(num_snapshots))
    print(" Total tag pairs (pooled): {}".format(len(all_rows)))
    print()
    if not all_rows:
        print(" No data to report.")
        return

    # Header
    fmt = "  {:<42s} {:>4s} {:>10s} {:>10s} {:>10s} {:>10s} {:>10s} {:>10s}"
    print(fmt.format("metric (unit)", "n", "mean", "median",
                     "std", "MAD", "p05", "p95"))
    print("  " + "-" * 116)

    for key, label, unit, _is_abs in SCALAR_METRICS:
        vals = [r[key] for r in all_rows]
        s = summarise(vals)
        line = "  {:<42s} {:>4d} {:>10.3f} {:>10.3f} {:>10.3f} {:>10.3f} {:>10.3f} {:>10.3f}".format(
            "{} ({})".format(label, unit),
            s["n"], s["mean"], s["median"], s["std"], s["mad"],
            s["p05"], s["p95"])
        print(line)
    print("=" * 78)
    print()


def write_csv(all_rows, path):
    if not all_rows:
        return
    keys = list(all_rows[0].keys())
    # Ensure snapshot index appears first if present
    if "snapshot" in keys:
        keys = ["snapshot"] + [k for k in keys if k != "snapshot"]
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in all_rows:
            w.writerow(r)
    rospy.loginfo("Wrote per-pair CSV: %s", path)


def write_histograms(all_rows, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    for key, label, unit, _is_abs in SCALAR_METRICS:
        vals = np.array([r[key] for r in all_rows], dtype=float)
        vals = vals[~np.isnan(vals)]
        if vals.size == 0:
            continue
        fig, ax = plt.subplots(figsize=(6, 3.5))
        # Freedman-Diaconis-ish bin count, capped
        n_bins = max(10, min(50, int(round(2 * np.cbrt(vals.size)))))
        ax.hist(vals, bins=n_bins, color="#4477aa", edgecolor="black",
                linewidth=0.3)
        ax.axvline(np.mean(vals), color="red", linewidth=1.0,
                   label="mean = {:.3f}".format(np.mean(vals)))
        ax.axvline(np.median(vals), color="orange", linewidth=1.0,
                   linestyle="--", label="median = {:.3f}".format(np.median(vals)))
        ax.set_xlabel("{} [{}]".format(label, unit))
        ax.set_ylabel("count")
        ax.set_title("{}  (n = {})".format(label, vals.size))
        ax.legend(loc="best", fontsize=8)
        ax.grid(True, linestyle=":", linewidth=0.5, alpha=0.6)
        fig.tight_layout()
        fname = "hist_{}.png".format(key)
        fig.savefig(os.path.join(out_dir, fname), dpi=140)
        plt.close(fig)
    rospy.loginfo("Wrote histograms to: %s", out_dir)


# ---------------------------------------------------------------------------
# Stdin trigger thread
# ---------------------------------------------------------------------------

class StdinTrigger(threading.Thread):
    """Background thread that pushes events onto an internal queue when the
    user hits ENTER (or types 'q'+ENTER to quit early). Using a thread keeps
    the rospy spinner / TF buffer running while we block on input()."""

    def __init__(self):
        super(StdinTrigger, self).__init__()
        self.daemon = True
        self._lock = threading.Lock()
        self._events = []   # 'snap' or 'quit'
        self._stop = threading.Event()

    def run(self):
        while not self._stop.is_set():
            try:
                line = sys.stdin.readline()
            except (KeyboardInterrupt, EOFError):
                with self._lock:
                    self._events.append("quit")
                return
            if line == "":  # EOF
                with self._lock:
                    self._events.append("quit")
                return
            line = line.strip().lower()
            with self._lock:
                if line in ("q", "quit", "exit"):
                    self._events.append("quit")
                    return
                else:
                    self._events.append("snap")

    def pop(self):
        with self._lock:
            if self._events:
                return self._events.pop(0)
            return None

    def stop(self):
        self._stop.set()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    rospy.init_node("apriltag_precision_test", anonymous=False)

    # ---- params ---------------------------------------------------------
    frame_pattern = rospy.get_param("~frame_pattern", "tag{:d}")
    parent_frame = rospy.get_param("~parent_frame", "base_link")
    tag_ids = rospy.get_param("~tag_ids", list(range(12)))
    if not isinstance(tag_ids, (list, tuple)):
        rospy.logfatal("~tag_ids must be a list of ints, got: %r", tag_ids)
        return
    tag_ids = [int(t) for t in tag_ids]
    num_snapshots = int(rospy.get_param("~num_snapshots", 5))
    output_dir = rospy.get_param(
        "~output_dir",
        os.path.expanduser("~/.ros/apriltag_precision"))
    lookup_timeout = float(rospy.get_param("~lookup_timeout", 0.5))

    # Validate frame_pattern early
    try:
        _ = frame_pattern.format(0)
    except (IndexError, KeyError, ValueError) as e:
        rospy.logfatal("~frame_pattern is invalid: %r (%s)", frame_pattern, e)
        return

    rospy.loginfo("apriltag_precision_test starting:")
    rospy.loginfo("  parent_frame  = %s", parent_frame)
    rospy.loginfo("  frame_pattern = %s", frame_pattern)
    rospy.loginfo("  tag_ids       = %s", tag_ids)
    rospy.loginfo("  num_snapshots = %d", num_snapshots)
    rospy.loginfo("  output_dir    = %s", output_dir)

    # ---- TF -------------------------------------------------------------
    tf_buffer = tf2_ros.Buffer(cache_time=rospy.Duration(30.0))
    _ = tf2_ros.TransformListener(tf_buffer)
    rospy.sleep(0.5)  # let the listener accumulate some history

    capture = TagSnapshotCapture(
        tf_buffer, parent_frame, frame_pattern, tag_ids,
        lookup_timeout=lookup_timeout)

    # ---- ground truth ---------------------------------------------------
    gt_poses = {tid: gt_pose_in_rh_sheet_frame(tid)
                for tid in tag_ids if tid in GROUND_TRUTH_PDF}
    missing = sorted(set(tag_ids) - set(gt_poses.keys()))
    if missing:
        rospy.logwarn("No ground-truth entry for tag IDs %s -- they will be "
                      "looked up but ignored in error stats.", missing)

    # ---- interactive loop ----------------------------------------------
    stdin = StdinTrigger()
    stdin.start()

    print()
    print("Ready. Hit ENTER in this terminal to capture each snapshot.")
    print("After {} snapshots a report will be produced.".format(num_snapshots))
    print("Type 'q'+ENTER (or send EOF) to finish early.")
    print()

    snapshots = []
    pooled_rows = []
    rate = rospy.Rate(20)

    while not rospy.is_shutdown() and len(snapshots) < num_snapshots:
        ev = stdin.pop()
        if ev == "quit":
            break
        if ev == "snap":
            snap = capture.capture()
            visible = sorted(snap.keys())
            print("  snapshot {} captured: {} tags visible -> {}".format(
                len(snapshots) + 1, len(visible), visible))
            if len(visible) < 2:
                print("  (need at least 2 tags for any pair; not pooling.)")
                snapshots.append(snap)
                continue
            rows = compute_pair_errors(snap, gt_poses)
            for r in rows:
                r["snapshot"] = len(snapshots) + 1
            pooled_rows.extend(rows)
            snapshots.append(snap)
            print("  -> pooled {} pair errors so far".format(len(pooled_rows)))
        rate.sleep()

    stdin.stop()

    # ---- report ---------------------------------------------------------
    print_report(pooled_rows, len(snapshots))

    if pooled_rows:
        os.makedirs(output_dir, exist_ok=True)
        csv_path = os.path.join(output_dir, "pair_errors.csv")
        write_csv(pooled_rows, csv_path)
        write_histograms(pooled_rows, output_dir)
        print("Outputs written to: {}".format(output_dir))
    else:
        print("No pair errors collected; nothing to write.")


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass